using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using SourceGeneratorToolkit;

namespace EfficientUnionGenerator;

[Generator(LanguageNames.CSharp)]
public partial class EfficientUnionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static cxt =>
        {
            cxt.AddSource(
                $"{AttributeNamespace}.{EfficientUnionAttributeName}.g.cs",
                EfficientUnionAttributeSource);
        });

        var sourceAttr = context.CompilationProvider
            .Select(static (compilation, token) => compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.UnionAttribute") is { });
        context.RegisterSourceOutput(sourceAttr, (context, isAvailable) =>
        {
            if (!isAvailable)
            {
                context.AddSource(
                    $"{AttributeNamespace}.UnionAttribute.g.cs",
                    CompilerServicesUnionAttributeSource);
            }
        });

        var sourceInterface = context.CompilationProvider
            .Select(static (compilation, token) => compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.IUnion") is { });
        context.RegisterSourceOutput(sourceInterface, (context, isAvailable) =>
        {
            if (!isAvailable)
            {
                context.AddSource(
                    $"{AttributeNamespace}.IUnion.g.cs",
                    CompilerServicesIUnionSource);
            }
        });

        var sourceUnion = context.SyntaxProvider.ForAttributeWithMetadataName(
            $"{AttributeNamespace}.{EfficientUnionAttributeName}",
            static (node, token) => true,
            PredicateUnionType);
        context.RegisterSourceOutput(sourceUnion, EmitUnionType);
    }


    private static UnionTypeDefinition PredicateUnionType(GeneratorAttributeSyntaxContext context, CancellationToken token)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var fullName = symbol.ToDisplayString();
        var candidateTypes = symbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Select(TypeCandidateDefinition.Create)
            .OfType<TypeCandidateDefinition>();
        var candidateUnmanagedTypes = ImmutableArray.CreateBuilder<TypeCandidateDefinition>();
        var candidateManagedTypes = ImmutableArray.CreateBuilder<TypeCandidateDefinition>();
        foreach (var type in candidateTypes)
        {
            (type.IsUnmanaged ? candidateUnmanagedTypes : candidateManagedTypes).Add(type);
        }
        UnmanagedFieldBitMaskMode mode;
        ulong bitMask;
        if (context.Attributes[0].ConstructorArguments.Length == 0)
        {
            mode = UnmanagedFieldBitMaskMode.Auto;
            bitMask = 0;
        }
        else if (context.Attributes[0].ConstructorArguments.Length == 2)
        {
            mode = (UnmanagedFieldBitMaskMode)(int)context.Attributes[0].ConstructorArguments[0].Value!;
            bitMask = (ulong)context.Attributes[0].ConstructorArguments[1].Value!;
        }
        else
        {
            throw new InvalidOperationException($"Unsupported bit mask type");
        }
        return new UnionTypeDefinition(
            fullName,
            candidateUnmanagedTypes.ToImmutable(),
            candidateManagedTypes.ToImmutable(),
            bitMask,
            mode,
            new SourceBuilder(context, false));
    }


    private static void EmitUnionType(SourceProductionContext context, UnionTypeDefinition source)
    {
        var sb = source.SourceBuilder;
        sb.AppendAutoGeneratedComment();
        sb.AppendLine("#nullable enable");
        sb.AppendNamespaceDeclaration();

        using (sb.BeginTargetTypeDeclare())
        {
            if (source.CandidateUnmanagedTypes.Length > 0)
            {
                if (source.BitMask == 0)
                {
                    sb.AppendLine($$"""
                                        private enum __TypeSpecifier
                                        {
                                            __Undefined = 0,
                                            {{source.CandidateUnmanagedTypes.Select(static t => $"{t.FieldName},").PreserveIndent()}}
                                        }

                                        [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]
                                        private struct __UnmanagedField
                                        {
                                            {{source.GetUnmanagedFieldDecl().PreserveIndent()}}
                                        }

                                        private readonly __UnmanagedField __unmanagedField;
                                        private readonly __TypeSpecifier __typeSpecifier;

                                        private bool HasUnmanagedValue => __typeSpecifier != __TypeSpecifier.__Undefined;
                                        private object? UnmanagedValue => __typeSpecifier switch
                                        {
                                            {{source.CandidateUnmanagedTypes.Select(static t => $"__TypeSpecifier.{t.FieldName} => __unmanagedField.{t.FieldName},").PreserveIndent()}}
                                            _ => null,
                                        };

                                        """);
                }
                else
                {
                    sb.AppendLine($$"""
                                        private enum __TypeSpecifier{{source.TypeIdentifierBaseType}}
                                        {
                                            __Undefined = 0,
                                        """);

                    if (source.UnmanagedFieldBitMaskMode == UnmanagedFieldBitMaskMode.Auto)
                    {
                        foreach (var (type, pattern) in source.CandidateUnmanagedTypes.Zip(GetBitPatterns(source.BitMask), static (x, y) => (x, y)))
                        {
                            sb.AppendLine($$"""
                                            {{type.FieldName}} = {{pattern}},
                                        """);
                        }
                    }
                    else
                    {
                        foreach (var type in source.CandidateUnmanagedTypes)
                        {
                            sb.AppendLine($$"""
                                            {{type.FieldName}} = {{type.EnumBitPattern}},
                                        """);
                        }
                    }

                    sb.AppendLine($$"""
                                        }

                                        private const __TypeSpecifier __typeSpecifierBitMask = unchecked((__TypeSpecifier){{source.BitMask}});

                                        [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]
                                        private struct __UnmanagedField
                                        {
                                            [System.Runtime.InteropServices.FieldOffset(0)] public __TypeSpecifier __typeSpecifier;
                                            {{source.GetUnmanagedFieldDecl().PreserveIndent()}}
                                        }

                                        private readonly __UnmanagedField __unmanagedField;
                                        private readonly __TypeSpecifier __typeSpecifier
                                        {
                                            get => __unmanagedField.__typeSpecifier & __typeSpecifierBitMask;
                                            init => __unmanagedField.__typeSpecifier |= value;
                                        }

                                        private bool HasUnmanagedValue => __typeSpecifier != __TypeSpecifier.__Undefined;
                                        private object? UnmanagedValue
                                        {
                                            get
                                            {
                                                var maskedField = __unmanagedField;
                                                maskedField.__typeSpecifier ^= __typeSpecifierBitMask;
                                                return __typeSpecifier switch
                                                {
                                                    {{source.CandidateUnmanagedTypes.Select(static t => $"__TypeSpecifier.{t.FieldName} => maskedField.{t.FieldName},").PreserveIndent()}}
                                                    _ => null,
                                                };
                                            }
                                        }

                                        """);

                }
                foreach (var type in source.CandidateUnmanagedTypes)
                {
                    sb.AppendLine($$"""
                                        public partial {{sb.TargetType.Name}}({{type.TypeName}} {{type.ConstructorParameterName}})
                                        {
                                            __unmanagedField = new()
                                            {
                                                {{type.FieldName}} = {{type.ConstructorParameterName}},
                                            };
                                        """);
                    if (source.UnmanagedFieldBitMaskMode == UnmanagedFieldBitMaskMode.Auto)
                    {
                        sb.AppendLine($$"""
                                            __typeSpecifier = __TypeSpecifier.{{type.FieldName}};
                                        """);
                    }
                    sb.AppendLine($$"""
                                        }

                                        public bool TryGetValue(out {{type.TypeName}} value)
                                        {
                                            if (__typeSpecifier == __TypeSpecifier.{{type.FieldName}})
                                            {
                                                value = __unmanagedField.{{type.FieldName}};
                                                return true;
                                            }
                                            else
                                            {
                                                value = default;
                                                return false;
                                            }
                                        }

                                        """);
                }
            }

            if (source.CandidateManagedTypes.Length > 0)
            {
                sb.AppendLine($$"""
                                        private readonly object? __managedField;

                                        """);

                foreach (var type in source.CandidateManagedTypes)
                {
                    sb.AppendLine($$"""
                                        public partial {{sb.TargetType.Name}}({{type.TypeName}} {{type.ConstructorParameterName}})
                                        {
                                            __managedField = {{type.ConstructorParameterName}};
                                        }

                                        public bool TryGetValue([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out {{type.TypeName}}? value)
                                        {
                                            if (__managedField is {{type.TypeName}} __casted)
                                            {
                                                value = __casted;
                                                return true;
                                            }
                                            else
                                            {
                                                value = default;
                                                return false;
                                            }
                                        }

                                        """);
                }
            }

            switch((source.CandidateUnmanagedTypes.Length > 0, source.CandidateManagedTypes.Length > 0))
            {
            case (true, true):
                sb.AppendLine($$"""
                                        public bool HasValue => HasUnmanagedValue || __managedField is not null;
                                        public object? Value => HasUnmanagedValue ? UnmanagedValue : __managedField;
                                        """);
                break;
            case (true, false):
                sb.AppendLine($$"""
                                        public bool HasValue => HasUnmanagedValue;
                                        public object? Value => UnmanagedValue;
                                        """);
                break;
            case (false, true):
                sb.AppendLine($$"""
                                        public bool HasValue => __managedField is not null;
                                        public object? Value => __managedField;
                                        """);
                break;
            case (false, false):
                sb.AppendLine($$"""
                                        public bool HasValue => false;
                                        public object? Value => null;
                                        """);
                break;
            default:
                throw new InvalidOperationException("never path");
            }
        }

        var hintName = $"EfficientUnionGenerator-{sb.GetPreferHintName()}";
        var sourceCode = sb.Build();
        context.AddSource(
            hintName,
            sourceCode
            );
    }


    private static IEnumerable<ulong> GetBitPatterns(ulong mask)
    {
        if (mask == 0UL)
        {
            yield return 0UL;
            yield break;
        }

        var positions = new List<int>();
        for (int bit = 0; bit < 64; bit++)
        {
            if ((mask & (1UL << bit)) != 0UL)
            {
                positions.Add(bit);
            }
        }

        int n = positions.Count;
        if (n == 0)
        {
            yield return 0UL;
            yield break;
        }

        static IEnumerable<ulong> recurse(List<int> positions, int idx, ulong current)
        {
            if (idx < 0)
            {
                yield return current;
                yield break;
            }

            foreach (var v in recurse(positions, idx - 1, current))
                yield return v;

            ulong bitValue = 1UL << positions[idx];
            foreach (var v in recurse(positions, idx - 1, current | bitValue))
                yield return v;
        }

        foreach (var p in recurse(positions, n - 1, 0UL))
            yield return p;
    }


    private sealed record UnionTypeDefinition(
        string TypeName,
        ImmutableArray<TypeCandidateDefinition> CandidateUnmanagedTypes,
        ImmutableArray<TypeCandidateDefinition> CandidateManagedTypes,
        ulong BitMask,
        UnmanagedFieldBitMaskMode UnmanagedFieldBitMaskMode,
        SourceBuilder SourceBuilder)
    {
        public string TypeIdentifierBaseType => BitMask switch
        {
            <= byte.MaxValue => " : byte",
            <= ushort.MaxValue => " : ushort",
            <= uint.MaxValue => " : uint",
            _ => " : ulong",
        };

        public IEnumerable<string> GetUnmanagedFieldDecl()
        {
            foreach (var type in CandidateUnmanagedTypes)
            {
                yield return $$"""
                    [System.Runtime.InteropServices.FieldOffset(0)] public {{type.TypeName}} {{type.FieldName}};
                    """;
            }
        }

        public override int GetHashCode()
        {
            var hash = (uint)TypeName.GetHashCode();
            foreach (var candidate in CandidateUnmanagedTypes)
            {
                hash = (hash << 13) | (hash >> 19);
                hash ^= (uint)candidate.GetHashCode();
            }
            foreach (var candidate in CandidateManagedTypes)
            {
                hash = (hash << 13) | (hash >> 19);
                hash ^= (uint)candidate.GetHashCode();
            }
            return (int)hash;
        }

        public bool Equals(UnionTypeDefinition? other)
        {
            if (other is null)
            {
                return false;
            }

            if (TypeName != other.TypeName)
            {
                return false;
            }

            if (CandidateUnmanagedTypes.Length != other.CandidateUnmanagedTypes.Length)
            {
                return false;
            }

            for (int i = 0; i < CandidateUnmanagedTypes.Length; i++)
            {
                if (CandidateUnmanagedTypes[i] != other.CandidateUnmanagedTypes[i])
                {
                    return false;
                }
            }

            if (CandidateManagedTypes.Length != other.CandidateManagedTypes.Length)
            {
                return false;
            }

            for (int i = 0; i < CandidateManagedTypes.Length; i++)
            {
                if (CandidateManagedTypes[i] != other.CandidateManagedTypes[i])
                {
                    return false;
                }
            }

            if (BitMask != other.BitMask)
            {
                return false;
            }

            if (UnmanagedFieldBitMaskMode != other.UnmanagedFieldBitMaskMode)
            {
                return false;
            }

            // SourceBuilder is not considered for equality as it is used for code generation and does not affect the identity of the union type definition.
            return true;
        }
    }

    private sealed record TypeCandidateDefinition(
        string TypeName,
        bool IsUnmanaged,
        string ConstructorParameterName,
        ulong EnumBitPattern
        )
    {
        private static string CreateSafeFileName(string typeName)
        {
            var sb = new StringBuilder();
            sb.Append("__");
            foreach (var c in typeName)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append($"_u{(int)c:X04}_");
                }
            }
            return sb.ToString();
        }

        public string FieldName { get; } = CreateSafeFileName(TypeName);

        public static TypeCandidateDefinition? Create(IMethodSymbol ctor)
        {
            if (ctor.MethodKind != MethodKind.Constructor)
            {
                return null;
            }
            if (ctor.DeclaredAccessibility != Accessibility.Public)
            {
                return null;
            }
            if (ctor.Parameters.Length != 1)
            {
                return null;
            }

            var param = ctor.Parameters[0];
            var typeName = param.Type.ToDisplayString();
            var isUnmanaged = param.Type.IsUnmanagedType;
            var constructorParameterName = param.Name;
            var enumBitPattern = ctor.GetAttributes()
                .FirstOrDefault(static attr => attr.AttributeClass?.ToDisplayString() == $"{AttributeNamespace}.{EnumBitPatternAttributeName}")
                ?.ConstructorArguments[0]
                .Value as ulong?
                ?? 0;
            return new TypeCandidateDefinition(typeName, isUnmanaged, constructorParameterName, enumBitPattern);
        }
    }
}
