using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using SourceGeneratorToolkit;

namespace EfficientUnionGenerator;
using static Constants;

[Generator(LanguageNames.CSharp)]
public partial class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static cxt =>
        {
            cxt.AddSource(
                $"{AttributeNamespace}.{EfficientUnionAttributeName}.g.cs",
                EfficientUnionAttributeSource);
        });

        var sourceAttr = context.CompilationProvider
            .Select(static (compilation, token) => compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.UnionAttribute") is { });
        context.RegisterSourceOutput(sourceAttr, (context, isAvailable) =>
        {
            if (!isAvailable)
            {
                context.AddSource(
                    $"{AttributeNamespace}.UnionAttribute.g.cs",
                    CompilerServicesUnionAttributeSource);
            }
        });

        var sourceInterface = context.CompilationProvider
            .Select(static (compilation, token) => compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.IUnion") is { });
        context.RegisterSourceOutput(sourceInterface, (context, isAvailable) =>
        {
            if (!isAvailable)
            {
                context.AddSource(
                    $"{AttributeNamespace}.IUnion.g.cs",
                    CompilerServicesIUnionSource);
            }
        });

        var sourceUnion = context.SyntaxProvider.ForAttributeWithMetadataName(
            $"{AttributeNamespace}.{EfficientUnionAttributeName}",
            static (node, token) => true,
            PredicateUnionType);
        context.RegisterSourceOutput(sourceUnion, EmitUnionType);
    }


    private static UnionTypeDefinition PredicateUnionType(GeneratorAttributeSyntaxContext context, CancellationToken token)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var fullName = symbol.ToDisplayString();
        var candidateTypes = symbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Select(TypeCandidateDefinition.Create)
            .OfType<TypeCandidateDefinition>();
        var candidateUnmanagedTypes = ImmutableArray.CreateBuilder<TypeCandidateDefinition>();
        var candidateManagedTypes = ImmutableArray.CreateBuilder<TypeCandidateDefinition>();
        foreach (var type in candidateTypes)
        {
            (type.IsUnmanaged ? candidateUnmanagedTypes : candidateManagedTypes).Add(type);
        }
        TypeIdentifierValueMode mode;
        ulong bitMask;
        if (context.Attributes[0].ConstructorArguments.Length == 0)
        {
            mode = TypeIdentifierValueMode.AutoAssign;
            bitMask = 0;
        }
        else if (context.Attributes[0].ConstructorArguments.Length == 2)
        {
            mode = (TypeIdentifierValueMode)(int)context.Attributes[0].ConstructorArguments[0].Value!;
            bitMask = (ulong)context.Attributes[0].ConstructorArguments[1].Value!;
        }
        else
        {
            throw new InvalidOperationException($"Unsupported bit mask type");
        }
        return new UnionTypeDefinition(
            fullName,
            candidateUnmanagedTypes.ToImmutable(),
            candidateManagedTypes.ToImmutable(),
            bitMask,
            mode
            ) { SourceBuilder = new SourceBuilder(context, false) };
    }


    private static void EmitUnionType(SourceProductionContext context, UnionTypeDefinition source)
    {
        var sb = source.SourceBuilder;
        var mode = source.TypeIdentifierValueMode;
        sb.AppendAutoGeneratedComment();
        sb.AppendLine("#nullable enable");
        sb.AppendNamespaceDeclaration();

        using (sb.BeginTargetTypeDeclare())
        {
            GenerateTypeSpecifierEnumDeclaration(source);

            if (source.CandidateUnmanagedTypes.Length > 0)
            {
                if (source.BitMask == 0)
                {
                    sb.AppendLine($$"""
                        [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]
                        private struct __UnmanagedField
                        {
                            {{source.GetUnmanagedFieldDecl().PreserveIndent()}}
                        }

                        private readonly __UnmanagedField __unmanagedField;
                        private readonly __TypeSpecifier __typeSpecifier;

                        private bool HasUnmanagedValue => __typeSpecifier != __TypeSpecifier.__Undefined || __defaultTypeSpecifierHasType;
                        private object? UnmanagedValue => __typeSpecifier switch
                        {
                            {{source.CandidateUnmanagedTypes.Select(static t => $"__TypeSpecifier.{t.FieldName} => __unmanagedField.{t.FieldName},").PreserveIndent()}}
                            _ => null,
                        };

                        """);
                }
                else
                {
                    sb.AppendLine($$"""
                        private const __TypeSpecifier __typeSpecifierBitMask = unchecked((__TypeSpecifier){{source.BitMask}});

                        [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]
                        private struct __UnmanagedField
                        {
                            [System.Runtime.InteropServices.FieldOffset(0)] public __TypeSpecifier __typeSpecifier;
                            {{source.GetUnmanagedFieldDecl().PreserveIndent()}}
                        }

                        private readonly __UnmanagedField __unmanagedField;
                        private readonly __TypeSpecifier __typeSpecifier
                        {
                            get => __unmanagedField.__typeSpecifier & __typeSpecifierBitMask;
                            init => __unmanagedField.__typeSpecifier |= value;
                        }
                        
                        private bool HasUnmanagedValue => __typeSpecifier != __TypeSpecifier.__Undefined || __defaultTypeSpecifierHasType;
                        private object? UnmanagedValue
                        {
                            get
                            {
                                var maskedField = __unmanagedField;
                                maskedField.__typeSpecifier &= ~__typeSpecifierBitMask;
                                return __typeSpecifier switch
                                {
                                    {{source.CandidateUnmanagedTypes.Select(static t => $"__TypeSpecifier.{t.FieldName} => maskedField.{t.FieldName},").PreserveIndent()}}
                                    _ => null,
                                };
                            }
                        }

                        """);

                }
                foreach (var type in source.CandidateUnmanagedTypes)
                {
                    if (!mode.IsLeaveWhenCreate)
                    {
                        sb.AppendLine($$"""
                            public partial {{sb.TargetType.Name}}({{type.TypeName}} {{type.ConstructorParameterName}})
                            {
                                __unmanagedField = new()
                                {
                                    {{type.FieldName}} = {{type.ConstructorParameterName}},
                                };
                                __typeSpecifier = __TypeSpecifier.{{type.FieldName}};
                            }
                            """);
                    }
                    else
                    {
                        sb.AppendLine($$"""
                            public partial {{sb.TargetType.Name}}({{type.TypeName}} {{type.ConstructorParameterName}})
                            {
                                __unmanagedField = new()
                                {
                                    {{type.FieldName}} = {{type.ConstructorParameterName}},
                                };
                            }
                            """);
                    }

                    if(source.BitMask == 0 || mode.IsLeaveWhenGet)
                    {
                        sb.AppendLine($$"""
                            public bool TryGetValue(out {{type.TypeName}} value)
                            {
                                if (__typeSpecifier == __TypeSpecifier.{{type.FieldName}})
                                {
                                    value = __unmanagedField.{{type.FieldName}};
                                    return true;
                                }
                                else
                                {
                                    value = default;
                                    return false;
                                }
                            }

                            """);
                    }
                    else
                    {
                        sb.AppendLine($$"""
                            public bool TryGetValue(out {{type.TypeName}} value)
                            {
                                if (__typeSpecifier == __TypeSpecifier.{{type.FieldName}})
                                {
                                    var maskedField = __unmanagedField;
                                    maskedField.__typeSpecifier &= ~__typeSpecifierBitMask;
                                    value = maskedField.{{type.FieldName}};
                                    return true;
                                }
                                else
                                {
                                    value = default;
                                    return false;
                                }
                            }

                            """);
                    }
                }
            }

            if (source.CandidateManagedTypes.Length > 0)
            {
                sb.AppendLine($$"""
                                        private readonly object? __managedField;

                                        """);

                foreach (var type in source.CandidateManagedTypes)
                {
                    sb.AppendLine($$"""
                                        public partial {{sb.TargetType.Name}}({{type.TypeName}} {{type.ConstructorParameterName}})
                                        {
                                            __managedField = {{type.ConstructorParameterName}};
                                        }

                                        public bool TryGetValue([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out {{type.TypeName}}? value)
                                        {
                                            if (__managedField is {{type.TypeName}} __casted)
                                            {
                                                value = __casted;
                                                return true;
                                            }
                                            else
                                            {
                                                value = default;
                                                return false;
                                            }
                                        }

                                        """);
                }
            }

            switch((source.CandidateUnmanagedTypes.Length > 0, source.CandidateManagedTypes.Length > 0))
            {
            case (true, true):
                sb.AppendLine($$"""
                                        public bool HasValue => HasUnmanagedValue || __managedField is not null;
                                        public object? Value => HasUnmanagedValue ? UnmanagedValue : __managedField;
                                        """);
                break;
            case (true, false):
                sb.AppendLine($$"""
                                        public bool HasValue => HasUnmanagedValue;
                                        public object? Value => UnmanagedValue;
                                        """);
                break;
            case (false, true):
                sb.AppendLine($$"""
                                        public bool HasValue => __managedField is not null;
                                        public object? Value => __managedField;
                                        """);
                break;
            case (false, false):
                sb.AppendLine($$"""
                                        public bool HasValue => false;
                                        public object? Value => null;
                                        """);
                break;
            default:
                throw new InvalidOperationException("never path");
            }
        }

        var hintName = sb.GetPreferHintName(prefix: "EfficientUnionGenerator-", suffix: ".g");
        var sourceCode = sb.Build();
        context.AddSource(
            hintName,
            sourceCode
            );
    }


    private static void GenerateTypeSpecifierEnumDeclaration(UnionTypeDefinition source)
    {
        var sb = source.SourceBuilder;
        var baseType = source.TypeIdentifierBaseType;
        var mode = source.TypeIdentifierValueMode;
        var bitMask = source.BitMask;
        var types = source.CandidateUnmanagedTypes;
        var defaultTypeSpecifierHasType = "false";
        sb.AppendLine($$"""
                                        private enum __TypeSpecifier{{baseType}}
                                        {
                                        """);

        if (mode.IsExplicitAssign)
        {
            foreach (var type in types)
            {
                sb.AppendLine($$"""
                                            {{type.FieldName}} = {{type.EnumBitPattern}},
                                        """);
                if (type.EnumBitPattern == 0)
                {
                    defaultTypeSpecifierHasType = "true";
                }
            }
        }
        else if(bitMask == 0)
        {
            var i = 1;
            foreach (var type in types)
            {
                sb.AppendLine($$"""
                                            {{type.FieldName}} = {{i}},
                                        """);
                ++i;
            }
        }
        else
        {
            foreach (var (type, pattern) in types.Zip(Helpers.GetBitPatterns(bitMask), static (x, y) => (x, y)))
            {
                sb.AppendLine($$"""
                                            {{type.FieldName}} = {{pattern}},
                                        """);
                if (type.EnumBitPattern == 0)
                {
                    defaultTypeSpecifierHasType = "true";
                }
            }
        }
        sb.AppendLine($$"""
                                        
                                            __Undefined = 0,
                                        }

                                        private const bool __defaultTypeSpecifierHasType = {{defaultTypeSpecifierHasType}};
                                        """);
    }


}
